### PR TITLE
Improve compatibility with other frameworks and future OMF.

### PR DESCRIPTION
**Pull request by bobthecow**
- Move all autoloaded functions to `functions/`, remove unnecessary init.

### CODE REVIEW

**Comment by derekstavis** [comment]
Hm, I see a `README.md` being moved to `functions/` directory. I believe something went wrong here :P

**Comment by bobthecow** [comment]
@derekstavis that's the other readme. There are two; this one belongs with the functions :)

**Comment by jhillyerd** [comment]
Manually pulled from bobthecow:fishier, successfully tested a few commands:
- pacin figlet
- pacloc pth
- paclsorphans
- pacreps figlet
- pacrmorphans
- pacupd

:+1:

**Comment by bobthecow** [comment]
Thanks @jhillyerd!

**Pull request merged**
